Use regex to check the plugin version

diff --git a/.github/workflows/deploy-standalone-plugins.yml b/.github/workflows/deploy-standalone-plugins.yml
--- a/.github/workflows/deploy-standalone-plugins.yml
+++ b/.github/workflows/deploy-standalone-plugins.yml
@@ -33,12 +33,13 @@ jobs:
         id: set-matrix
         run: |
           if ${{ github.event_name == 'workflow_dispatch' }}; then
-            if ${{ steps.get-version.outputs.version == '' }}; then
-              echo "The ${{ inputs.slug }} module slug is missing in the file plugins.json."
-              exit 1
-            else
+            result=$(echo "${{ steps.get-version.outputs.version }}" | awk '/^(\*|[0-9]+(\.[0-9]+){0,2}(-[a-zA-Z0-9.]+)?)$/ {print "Matched"}')
+            if [[ -n "$result" ]]; then
               # Set the manual input values in JSON format for use in the matrix.
               echo "matrix={\"include\":[{\"slug\":\"${{ inputs.slug }}\",\"version\":\"${{ steps.get-version.outputs.version }}\"}]}" >> $GITHUB_OUTPUT
+            else
+              echo "The ${{ inputs.slug }} module slug is missing in the file plugins.json."
+              exit 1
             fi
           else
             # Load the JSON file and parse from "{name: {slug, version}, ...}" to "include: [{ name, slug, version }, ...]"
