Refactor version parsing to improve error handling
Co-authored-by: Weston Ruter <westonruter@google.com>

diff --git a/.github/workflows/update-wp-compatibility.yml b/.github/workflows/update-wp-compatibility.yml
--- a/.github/workflows/update-wp-compatibility.yml
+++ b/.github/workflows/update-wp-compatibility.yml
@@ -55,9 +55,17 @@ jobs:
             exit 1
           fi
 
-          WP_ORG_VERSION=$(grep -E "^Tested up to:" /tmp/wp-org-readme.txt | sed -E 's/Tested up to:[[:space:]]*([0-9.]+)/\1/')
-          REPO_VERSION=$(grep -E "^Tested up to:" ./plugins/${{ matrix.plugin }}/readme.txt | sed -E 's/Tested up to:[[:space:]]*([0-9.]+)/\1/')
+          WP_ORG_VERSION=$(grep -E "^Tested up to:" /tmp/wp-org-readme.txt | awk -F ': +' '{print $2}')
+          REPO_VERSION=$(grep -E "^Tested up to:" ./plugins/${{ matrix.plugin }}/readme.txt | awk -F ': +' '{print $2}')
 
+          if [ -n "$WP_ORG_VERSION" ]; then
+            echo "Unable to parse WP_ORG_VERSION"
+            exit 1
+          fi
+          if [ -n "$REPO_VERSION" ]; then
+            echo "Unable to parse REPO_VERSION"
+            exit 1
+          fi
           echo "wp_org_version=$WP_ORG_VERSION" >> $GITHUB_OUTPUT
           echo "repo_version=$REPO_VERSION" >> $GITHUB_OUTPUT
 
